### ISSUE TITLE
Error when reading DB information in Windows 11 ARM for MariaDB

### ISSUE THREAD

**Issue by AnsonWooBizCloud** [KS-DB-Merge-Tools/Issues#11] opened 2024-11-23 04:27 UTC
It is the log:

Reading database 10.68.40.192.DB..
Reading sequences.
Reading sequence definitions
Reading tables list...........................
Reading table columns............................
Reading table constraints.........................................
Reading foreign keys................................
Reading table definitions..............................................................................................................................................................................................................................................................................................
Reading indexes...........................................
Reading triggers....
Reading view definitions.
Local cache initialization error: The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception.
Reading view columns.
Reading stored procedures............
Reading stored procedures parameters.........
Local cache initialization error: The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception.
The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception. (Exception has been thrown by the target of an invocation.)
Reading database - done
Failed to load some objects from [DB] on 10.68.40.192:3306. Check the errors above in this list.

It seems only occurs in ARM version because I have another Windows 11 x64 VM that works fine.

**Comment by semenenkov** [comment] 2024-11-23 05:28
@AnsonWooBizCloud thanks a lot for reporting this issue!

Historically most of KS DB Merge Tools are x86 which also works on x64, few of them include also x64 binaries to avoid out-of-memory for huge dbs. ARM is currently not supported.

App fails because of SQLite platform-specific dependency, SQLite is used for local cache. The error does not look critical and most likely can be fixed by adding arm sqlite dll, just one file. But I currently don't have ARM system to verify the fix, and the bigger issue is that if I start to support ARM then I need to run some ARM tests on each release.

However I understand importance of this, ARM market share seems to be growing. I'll provide an update in few days.

**Comment by semenenkov** [comment] 2024-12-10 17:12
Ok, I've made Win11 ARM in QEMU, extremely slow but I reproduced the issue and I think I have a workaround. It seems that SQLitePCL dependency tries to use ARM64 native library instead of x86 (the whole process is running as x86 emulation and it should use x86 library). The workaround is to make a copy of app_folder\runtimes\win-x86\native\e_sqlite3.dll to app_folder\e_sqlite3.dll, just please don't forget to remove it before installing upgrades.

Now I need to think of a more general fix, because I was going to include x64 binary for MySQL tool like it is already done for some other tools but different bitness can't use the same dll. Maybe I'll change the tool to be x64.

**Comment by semenenkov** [comment] 2024-12-13 07:39
Fixed in 1.19.0

**Closed as completed by semenenkov** 2024-12-13 07:39 UTC

**Comment by semenenkov** [comment] 2024-12-13 07:41
Fixed for 32-bit version. 1.19.0 also includes 64-bit version which does not support Windows ARM.

**Comment by AnsonWooBizCloud** [comment] 2024-12-19 05:53
Tested and come back to say Thank You!
